In [1]:
import tensorflow as tf
print(tf.__version__)

physical_device = tf.config.experimental.list_physical_devices("GPU")
if len(physical_device) > 0:
    tf.config.experimental.set_memory_growth(physical_device[0], True)

2.2.0


In [3]:
example_tensor = tf.random.uniform([3, 2])
print(example_tensor.shape)

(3, 2)


In [4]:
dataset1 = tf.data.Dataset.from_tensor_slices(example_tensor)
dataset2 = tf.data.Dataset.from_tensors(example_tensor)

In [5]:
print(dataset1.element_spec)
print(dataset2.element_spec)

TensorSpec(shape=(2,), dtype=tf.float32, name=None)
TensorSpec(shape=(3, 2), dtype=tf.float32, name=None)


In [6]:
tensor1 = tf.random.uniform([10, 2, 2])
tensor2 = tf.random.uniform([10, 1])
tensor3 = tf.random.uniform([9, 2, 2])

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor3))

ValueError: Dimensions 10 and 9 are not compatible

In [11]:
dataset = tf.data.Dataset.from_tensors((tensor1, tensor3))
dataset.element_spec

(TensorSpec(shape=(10, 2, 2), dtype=tf.float32, name=None),
 TensorSpec(shape=(9, 2, 2), dtype=tf.float32, name=None))

In [12]:
dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor2))
dataset.element_spec

(TensorSpec(shape=(2, 2), dtype=tf.float32, name=None),
 TensorSpec(shape=(1,), dtype=tf.float32, name=None))

In [13]:
import numpy as np

numpy_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(numpy_array.shape)

(3, 2, 2)


In [14]:
dataset1 = tf.data.Dataset.from_tensor_slices(numpy_array)
dataset2 = tf.data.Dataset.from_tensors(numpy_array)

print(dataset1.element_spec)
print(dataset2.element_spec)

TensorSpec(shape=(2, 2), dtype=tf.int64, name=None)
TensorSpec(shape=(3, 2, 2), dtype=tf.int64, name=None)


In [15]:
import pandas as pd

df = pd.read_csv('data/balloon_dataset.csv')
df.head()

Colour   Size      Act    Age Inflated
0  YELLOW  SMALL  STRETCH  ADULT        T
1  YELLOW  SMALL  STRETCH  ADULT        T
2  YELLOW  SMALL  STRETCH  CHILD        F
3  YELLOW  SMALL      DIP  ADULT        F
4  YELLOW  SMALL      DIP  CHILD        F

In [16]:
df_dict = dict(df)
print(df_dict.keys())

dict_keys(['Colour', 'Size', 'Act', 'Age', 'Inflated'])


In [17]:
pandas_dataset = tf.data.Dataset.from_tensor_slices(df_dict)
pandas_dataset.element_spec

{'Colour': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Size': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Act': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Age': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Inflated': TensorSpec(shape=(), dtype=tf.string, name=None)}

In [18]:
next(iter(pandas_dataset))

{'Colour': <tf.Tensor: shape=(), dtype=string, numpy=b'YELLOW'>,
 'Size': <tf.Tensor: shape=(), dtype=string, numpy=b'SMALL'>,
 'Act': <tf.Tensor: shape=(), dtype=string, numpy=b'STRETCH'>,
 'Age': <tf.Tensor: shape=(), dtype=string, numpy=b'ADULT'>,
 'Inflated': <tf.Tensor: shape=(), dtype=string, numpy=b'T'>}

In [19]:
csv_dataset = tf.data.experimental.make_csv_dataset('data/balloon_dataset.csv',
                                                    batch_size=1,
                                                    label_name='Inflated')

In [20]:
csv_dataset.element_spec

(OrderedDict([('Colour', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Size', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Act', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Age', TensorSpec(shape=(1,), dtype=tf.string, name=None))]),
 TensorSpec(shape=(1,), dtype=tf.string, name=None))

In [21]:
next(iter(csv_dataset))

(OrderedDict([('Colour',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'PURPLE'], dtype=object)>),
              ('Size',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'SMALL'], dtype=object)>),
              ('Act',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'DIP'], dtype=object)>),
              ('Age',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'CHILD'], dtype=object)>)]),
 <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'F'], dtype=object)>)